# Generated by Django 5.0.1 on 2024-05-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clientloginsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientloginsession',
            name='username',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
