# Generated by Django 5.0.1 on 2024-06-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_clientloginsession_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLoginFailedSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.GenericIPAddressField()),
                ('username', models.CharField(max_length=200)),
                ('failed_count', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ClientLoginSession',
        ),
    ]
