# Generated by Django 5.0.1 on 2024-06-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clientloginfailedsession_delete_clientloginsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientloginfailedsession',
            name='failed_count',
            field=models.IntegerField(default=0),
        ),
    ]
