# Generated by Django 4.2.6 on 2024-07-19 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckpointPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.CharField(max_length=200, unique=True)),
                ('layer', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckpointSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=100, unique=True)),
                ('smc', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='F5Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f5_device_ip', models.CharField(max_length=200)),
                ('f5_device_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='F5PoolMemberMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_method', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='F5Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=200, unique=True)),
                ('partition', models.CharField(blank=True, max_length=200)),
                ('protocol', models.CharField(blank=True, max_length=200)),
                ('client_protocol_profile', models.CharField(blank=True, max_length=200)),
                ('server_protocol_profile', models.CharField(blank=True, max_length=200)),
                ('client_http_profile', models.CharField(blank=True, max_length=200)),
                ('server_http_profile', models.CharField(blank=True, max_length=200)),
                ('snat_name', models.CharField(blank=True, max_length=200)),
                ('http_analytics_profile', models.CharField(blank=True, max_length=200)),
                ('tcp_analytics_profile', models.CharField(blank=True, max_length=200)),
                ('web_socket_profile', models.CharField(blank=True, max_length=200)),
                ('http_compression_profile', models.CharField(blank=True, max_length=200)),
                ('web_acceleration_profile', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CheckpointRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('source', models.CharField(max_length=1000)),
                ('destination', models.CharField(max_length=1000)),
                ('protocol', models.CharField(max_length=1000)),
                ('schedule', models.CharField(blank=True, max_length=1000)),
                ('section', models.CharField(blank=True, max_length=100)),
                ('user_created', models.CharField(max_length=200)),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=200)),
                ('message', models.CharField(blank=True, max_length=3000, null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cm.checkpointpolicy')),
            ],
        ),
        migrations.CreateModel(
            name='CheckpointRuleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=100)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cm.checkpointpolicy')),
            ],
        ),
        migrations.AddField(
            model_name='checkpointpolicy',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cm.checkpointsite'),
        ),
        migrations.CreateModel(
            name='F5ClientSSLProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=200)),
                ('f5_device_ip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cm.f5device')),
            ],
        ),
        migrations.CreateModel(
            name='F5Irule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irule_name', models.CharField(max_length=200)),
                ('f5_device_ip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cm.f5device')),
            ],
        ),
        migrations.CreateModel(
            name='F5PoolMemberMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_monitor', models.CharField(max_length=200)),
                ('f5_device_ip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cm.f5device')),
            ],
        ),
        migrations.CreateModel(
            name='F5ServerSSLProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=200)),
                ('f5_device_ip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cm.f5device')),
            ],
        ),
        migrations.CreateModel(
            name='F5CreateVirtualServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('vs_name', models.CharField(max_length=200)),
                ('vs_ip', models.GenericIPAddressField()),
                ('vs_port', models.IntegerField()),
                ('pool_name', models.CharField(max_length=200)),
                ('pool_member', models.CharField(max_length=1000)),
                ('pool_monitor', models.CharField(max_length=200)),
                ('pool_lb_method', models.CharField(max_length=200)),
                ('client_ssl_profile', models.CharField(blank=True, max_length=200)),
                ('server_ssl_profile', models.CharField(blank=True, max_length=200)),
                ('irules', models.CharField(blank=True, max_length=200)),
                ('waf_profile', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('message', models.CharField(blank=True, max_length=1000)),
                ('user_created', models.CharField(max_length=200)),
                ('f5_device_ip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cm.f5device')),
                ('f5_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cm.f5template')),
            ],
        ),
        migrations.CreateModel(
            name='F5WafProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waf_profile', models.CharField(max_length=200)),
                ('f5_device_ip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cm.f5device')),
            ],
        ),
    ]
