# Generated by Django 4.2.6 on 2024-03-25 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CheckpointTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('source', models.CharField(max_length=1000)),
                ('destination', models.CharField(max_length=1000)),
                ('protocol', models.CharField(max_length=1000)),
                ('schedule', models.CharField(max_length=1000)),
                ('message', models.CharField(max_length=3000)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cm.taskstatus')),
            ],
        ),
    ]
