# Generated by Django 5.0.1 on 2024-07-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='f5template',
            name='web_socket_profile',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
