# Generated by Django 4.2.6 on 2024-03-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointtask',
            name='time_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='checkpointtask',
            name='user_created',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
