# Generated by Django 5.0.1 on 2024-06-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='f5template',
            name='waf_profile',
        ),
        migrations.AddField(
            model_name='f5template',
            name='waf_profile',
            field=models.ManyToManyField(blank=True, null=True, to='cm.f5wafprofile'),
        ),
    ]
