# Generated by Django 5.0.1 on 2024-06-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0002_remove_f5template_waf_profile_f5template_waf_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='f5template',
            name='irules',
        ),
        migrations.RemoveField(
            model_name='f5template',
            name='waf_profile',
        ),
        migrations.AddField(
            model_name='f5template',
            name='irules',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='f5template',
            name='waf_profile',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
