# Generated by Django 4.2.6 on 2024-03-25 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0002_checkpointtask_time_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckpointSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CheckpointPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.CharField(max_length=500)),
                ('site_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cm.checkpointsite')),
            ],
        ),
    ]
