# Generated by Django 4.2.6 on 2024-07-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0002_remove_f5template_client_http_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='f5template',
            name='client_http_profile',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='f5template',
            name='client_protocol_profile',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='f5template',
            name='http_analytics_profile',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='f5template',
            name='http_compression_profile',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='f5template',
            name='partition',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='f5template',
            name='protocol',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='f5template',
            name='server_http_profile',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='f5template',
            name='server_protocol_profile',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='f5template',
            name='snat_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='f5template',
            name='tcp_analytics_profile',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='f5template',
            name='web_acceleration_profile',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
