# Generated by Django 5.0.3 on 2024-03-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0003_checkpointsite_checkpointpolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpointtask',
            name='status',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='checkpointpolicy',
            name='policy',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='checkpointsite',
            name='site_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='checkpointtask',
            name='message',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
    ]
