# Generated by Django 5.0.1 on 2024-06-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0003_remove_f5template_irules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f5template',
            name='irules',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='f5template',
            name='waf_profile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
