# Generated by Django 5.0.1 on 2024-07-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0003_f5template_client_http_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f5createvirtualserver',
            name='irules',
            field=models.CharField(blank=True, default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='f5createvirtualserver',
            name='waf_profile',
            field=models.CharField(blank=True, default=1, max_length=200),
            preserve_default=False,
        ),
    ]
