# Generated by Django 5.0.1 on 2024-07-04 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0004_alter_f5createvirtualserver_irules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='f5createvirtualserver',
            name='pool_lb_method',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='f5createvirtualserver',
            name='pool_monitor',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='F5PoolMemberMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_method', models.CharField(max_length=200)),
                ('f5_device_ip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cm.f5device')),
            ],
        ),
        migrations.CreateModel(
            name='F5PoolMemberMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_monitor', models.CharField(max_length=200)),
                ('f5_device_ip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cm.f5device')),
            ],
        ),
    ]
