# Generated by Django 5.0.1 on 2024-06-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0004_alter_f5template_irules_alter_f5template_waf_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='f5template',
            name='irules',
        ),
        migrations.AddField(
            model_name='f5template',
            name='irules',
            field=models.ManyToManyField(blank=True, null=True, to='cm.f5irule'),
        ),
    ]
