# Generated by Django 5.0.3 on 2024-03-26 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0004_alter_checkpointtask_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpointtask',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cm.checkpointpolicy'),
        ),
    ]
