# Generated by Django 4.2.6 on 2024-07-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0005_f5createvirtualserver_pool_lb_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='f5poolmembermethod',
            name='f5_device_ip',
        ),
    ]
