# Generated by Django 5.0.3 on 2024-03-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0005_alter_checkpointtask_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointsite',
            name='cp_smc',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='checkpointsite',
            name='cp_smc_layer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkpointsite',
            name='cp_smc_section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
