# Generated by Django 5.0.1 on 2024-06-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0005_remove_f5template_irules_f5template_irules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f5template',
            name='waf_profile',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
