# Generated by Django 5.0.1 on 2024-06-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0006_alter_f5template_waf_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f5template',
            name='irules',
            field=models.ManyToManyField(blank=True, default=None, to='cm.f5irule'),
        ),
        migrations.AlterField(
            model_name='f5template',
            name='waf_profile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
