# Generated by Django 5.0.3 on 2024-03-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0006_checkpointsite_cp_smc_checkpointsite_cp_smc_layer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkpointpolicy',
            old_name='policy',
            new_name='cp_smc_policy',
        ),
        migrations.RemoveField(
            model_name='checkpointsite',
            name='cp_smc_layer',
        ),
        migrations.RemoveField(
            model_name='checkpointsite',
            name='cp_smc_section',
        ),
        migrations.AddField(
            model_name='checkpointpolicy',
            name='cp_smc_layer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkpointpolicy',
            name='cp_smc_section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
