# Generated by Django 5.0.3 on 2024-03-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0007_rename_policy_checkpointpolicy_cp_smc_policy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkpointpolicy',
            old_name='cp_smc_layer',
            new_name='layer',
        ),
        migrations.RenameField(
            model_name='checkpointpolicy',
            old_name='cp_smc_policy',
            new_name='policy',
        ),
        migrations.RenameField(
            model_name='checkpointpolicy',
            old_name='cp_smc_section',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='checkpointpolicy',
            old_name='site_name',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='checkpointsite',
            old_name='site_name',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='checkpointsite',
            old_name='cp_smc',
            new_name='smc',
        ),
    ]
