# Generated by Django 5.0.3 on 2024-03-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0008_rename_cp_smc_layer_checkpointpolicy_layer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpointsite',
            name='smc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
