# Generated by Django 5.0.1 on 2024-04-04 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0009_alter_checkpointsite_smc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckpointTask',
            new_name='CheckpointRule',
        ),
    ]
