# Generated by Django 5.0.1 on 2024-04-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0010_rename_checkpointtask_checkpointrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpointrule',
            name='schedule',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
