# Generated by Django 5.0.1 on 2024-06-05 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0011_alter_checkpointrule_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='LBCreateVirtualServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('vs_name', models.CharField(max_length=200)),
                ('vs_ip', models.GenericIPAddressField()),
                ('vs_port', models.IntegerField()),
                ('pool_name', models.CharField(max_length=200)),
                ('client_ssl_profile', models.CharField(max_length=200)),
                ('server_ssl_profile', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LBDeviceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LBDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_ip', models.GenericIPAddressField()),
                ('device_name', models.CharField(max_length=200)),
                ('device_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cm.lbdevicecategory')),
            ],
        ),
    ]
