# Generated by Django 5.0.1 on 2024-06-07 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0012_lbcreatevirtualserver_lbdevicecategory_lbdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='F5CreateVirtualServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('vs_name', models.CharField(max_length=200)),
                ('vs_ip', models.GenericIPAddressField()),
                ('vs_port', models.IntegerField()),
                ('pool_name', models.CharField(max_length=200)),
                ('client_ssl_profile', models.CharField(max_length=200)),
                ('server_ssl_profile', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='F5Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_ip', models.GenericIPAddressField()),
                ('device_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='LBCreateVirtualServer',
        ),
        migrations.AddField(
            model_name='f5createvirtualserver',
            name='f5_device_ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cm.f5device'),
        ),
        migrations.DeleteModel(
            name='LBDevice',
        ),
        migrations.DeleteModel(
            name='LBDeviceCategory',
        ),
    ]
