# Generated by Django 4.2.6 on 2024-06-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0013_f5createvirtualserver_f5device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='f5device',
            name='snat_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
