# Generated by Django 4.2.6 on 2024-06-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0014_f5device_snat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='f5createvirtualserver',
            name='pool_member',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
