# Generated by Django 4.2.6 on 2024-06-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0015_f5createvirtualserver_pool_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='f5createvirtualserver',
            name='user_created',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
