# Generated by Django 5.0.1 on 2024-06-12 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0016_f5createvirtualserver_user_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='f5device',
            old_name='device_ip',
            new_name='f5_device_ip',
        ),
        migrations.RenameField(
            model_name='f5device',
            old_name='device_name',
            new_name='f5_device_name',
        ),
        migrations.CreateModel(
            name='F5ClientSSLProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=200)),
                ('f5_device_ip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cm.f5device')),
            ],
        ),
        migrations.CreateModel(
            name='F5ServerSSLProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=200)),
                ('f5_device_ip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cm.f5device')),
            ],
        ),
    ]
