# Generated by Django 5.0.1 on 2024-06-12 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0017_rename_device_ip_f5device_f5_device_ip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='f5device',
            name='snat_name',
        ),
        migrations.CreateModel(
            name='F5SNAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snat_name', models.CharField(max_length=200)),
                ('f5_device_ip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cm.f5device')),
            ],
        ),
    ]
