# Generated by Django 5.0.1 on 2024-06-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0018_remove_f5device_snat_name_f5snat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f5createvirtualserver',
            name='client_ssl_profile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='f5createvirtualserver',
            name='server_ssl_profile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
