# Generated by Django 5.0.1 on 2024-06-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0019_alter_f5createvirtualserver_client_ssl_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f5createvirtualserver',
            name='client_ssl_profile',
            field=models.CharField(blank=True, default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='f5createvirtualserver',
            name='server_ssl_profile',
            field=models.CharField(blank=True, default=1, max_length=200),
            preserve_default=False,
        ),
    ]
