# Generated by Django 4.2.6 on 2024-06-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0020_alter_f5createvirtualserver_client_ssl_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='f5createvirtualserver',
            name='message',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='f5createvirtualserver',
            name='status',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
