# Generated by Django 5.0.2 on 2024-02-26 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_category', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_location', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_os', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_vendor', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(blank=True, max_length=200)),
                ('device_ip', models.GenericIPAddressField(unique=True)),
                ('device_firmware', models.CharField(blank=True, max_length=200, null=True)),
                ('device_stack', models.BooleanField(blank=True, default=False, null=True)),
                ('device_description', models.CharField(blank=True, max_length=200, null=True)),
                ('device_creation_time', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(blank=True, max_length=100, null=True)),
                ('device_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.devicecategory')),
                ('device_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.devicelocation')),
                ('device_os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.deviceos')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.devicetype')),
                ('device_vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.devicevendor')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_config_standardized', models.BooleanField(blank=True, null=True)),
                ('device_monitored', models.BooleanField(blank=True, null=True)),
                ('device_backup_config', models.BooleanField(blank=True, null=True)),
                ('user_created', models.CharField(blank=True, max_length=100, null=True)),
                ('device_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_interface_name', models.JSONField(blank=True, max_length=200, null=True)),
                ('list_interface_desc', models.JSONField(blank=True, max_length=200, null=True)),
                ('list_interface_speed', models.JSONField(blank=True, max_length=200, null=True)),
                ('list_interface_type', models.JSONField(blank=True, max_length=200, null=True)),
                ('list_interface_state', models.JSONField(blank=True, max_length=200, null=True)),
                ('user_created', models.CharField(blank=True, max_length=100, null=True)),
                ('device_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_serial_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('start_ma_date', models.DateField(blank=True, null=True)),
                ('end_ma_date', models.DateField(blank=True, null=True)),
                ('start_license_date', models.DateField(blank=True, null=True)),
                ('end_license_date', models.DateField(blank=True, null=True)),
                ('end_sw_support_date', models.DateField(blank=True, null=True)),
                ('end_hw_support_date', models.DateField(blank=True, null=True)),
                ('start_used_date', models.DateField(blank=True, null=True)),
                ('user_created', models.CharField(blank=True, max_length=100, null=True)),
                ('device_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceTopology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_rack_name', models.CharField(blank=True, max_length=200, null=True)),
                ('device_rack_unit', models.IntegerField(blank=True, null=True)),
                ('user_created', models.CharField(blank=True, max_length=100, null=True)),
                ('device_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceFirmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmware', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(blank=True, max_length=100, null=True)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.devicetype')),
            ],
        ),
    ]
