# Generated by Django 4.2.6 on 2023-10-16 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_category', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_location', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=1000)),
                ('device_ip', models.GenericIPAddressField()),
                ('device_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.devicecategory')),
                ('device_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.devicelocation')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.devicetype')),
            ],
        ),
    ]
