# Generated by Django 4.2.6 on 2024-03-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinterface',
            name='list_interface_desc',
            field=models.JSONField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='deviceinterface',
            name='list_interface_name',
            field=models.JSONField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='deviceinterface',
            name='list_interface_speed',
            field=models.JSONField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='deviceinterface',
            name='list_interface_state',
            field=models.JSONField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='deviceinterface',
            name='list_interface_type',
            field=models.JSONField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='deviceinterface',
            name='user_created',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
