# Generated by Django 4.2.6 on 2024-04-11 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_deviceinterface_list_interface_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_branch', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_tag', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='device_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.devicebranch'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.devicetag'),
        ),
    ]
