# Generated by Django 4.2.6 on 2023-10-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_devicecategory_creation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecategory',
            name='device_category',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='devicelocation',
            name='device_location',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='device_ip',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='device_type',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='devicevendor',
            name='device_vendor',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
