# Generated by Django 4.2.6 on 2023-10-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_devicecategory_device_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecategory',
            name='user_created',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='user_created',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='user_created',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicetype',
            name='user_created',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicevendor',
            name='user_created',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
