# Generated by Django 4.2.6 on 2024-04-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_devicelocation_deviceprovince_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='device_location',
            new_name='device_province',
        ),
    ]
