# Generated by Django 4.2.6 on 2023-10-23 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_devicecategory_user_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='device_vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.devicevendor'),
            preserve_default=False,
        ),
    ]
