# Generated by Django 5.0.1 on 2024-04-12 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_device_location_device_device_province'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceTopology',
            new_name='DeviceRackLayout',
        ),
    ]
