# Generated by Django 4.2.6 on 2023-10-30 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory",
            "0007_rename_devicemodel_devicebaseinfo_devicemanagement_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deviceinterface",
            name="list_interface",
        ),
        migrations.RemoveField(
            model_name="deviceinterface",
            name="list_interface_neighbor",
        ),
        migrations.AddField(
            model_name="deviceinterface",
            name="list_interface_desc",
            field=models.JSONField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deviceinterface",
            name="list_interface_name",
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deviceinterface",
            name="list_interface_neghbor",
            field=models.JSONField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deviceinterface",
            name="list_interface_state",
            field=models.JSONField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deviceinterface",
            name="list_interface_type",
            field=models.JSONField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="deviceinterface",
            name="list_interface_inuse",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="deviceinterface",
            name="list_interface_speed",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="deviceinterface",
            name="list_interface_unuse",
            field=models.JSONField(),
        ),
        migrations.CreateModel(
            name="DeviceTopology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_rack_name", models.CharField(max_length=1000)),
                ("device_rack_unit", models.CharField(max_length=1000)),
                (
                    "device_ip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.devicebaseinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_config_standardized", models.BooleanField()),
                ("device_monitored", models.BooleanField()),
                ("device_backup_config", models.BooleanField()),
                (
                    "device_ip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.devicebaseinfo",
                    ),
                ),
            ],
        ),
    ]
