# Generated by Django 4.2.6 on 2023-10-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_remove_deviceinterface_list_interface_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceinterface",
            name="list_interface_name",
            field=models.JSONField(max_length=1000),
        ),
    ]
