# Generated by Django 4.2.6 on 2023-10-30 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_alter_deviceinterface_list_interface_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicemanagement",
            name="device_serial_number",
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="DeviceBasicInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_name", models.CharField(blank=True, max_length=1000)),
                ("device_ip", models.GenericIPAddressField(unique=True)),
                ("device_description", models.CharField(blank=True, max_length=1000)),
                ("device_creation_time", models.DateTimeField(auto_now=True)),
                ("user_created", models.CharField(max_length=100)),
                (
                    "device_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.devicecategory",
                    ),
                ),
                (
                    "device_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.devicelocation",
                    ),
                ),
                (
                    "device_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.devicetype",
                    ),
                ),
                (
                    "device_vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.devicevendor",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="deviceconfiguration",
            name="device_ip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.devicebasicinfo",
            ),
        ),
        migrations.AlterField(
            model_name="deviceinterface",
            name="device_ip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.devicebasicinfo",
            ),
        ),
        migrations.AlterField(
            model_name="devicemanagement",
            name="device_ip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.devicebasicinfo",
            ),
        ),
        migrations.AlterField(
            model_name="devicetopology",
            name="device_ip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.devicebasicinfo",
            ),
        ),
        migrations.DeleteModel(
            name="DeviceBaseInfo",
        ),
    ]
