# Generated by Django 4.2.6 on 2023-11-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_devicemanagement_device_serial_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceinterface',
            old_name='list_interface_neghbor',
            new_name='list_interface_neighbor',
        ),
        migrations.AlterField(
            model_name='deviceinterface',
            name='list_interface_name',
            field=models.JSONField(),
        ),
    ]
