# Generated by Django 4.2.6 on 2024-01-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_devicebasicinfo_device_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetopology',
            name='device_rack_unit',
            field=models.IntegerField(),
        ),
    ]
