# Generated by Django 4.2.6 on 2024-02-01 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0013_alter_devicetopology_device_rack_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceOS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_os", models.CharField(max_length=200, unique=True)),
                ("description", models.CharField(max_length=200)),
                ("creation_time", models.DateTimeField(auto_now=True)),
                ("user_created", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="devicebasicinfo",
            name="device_os",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.deviceos",
            ),
            preserve_default=False,
        ),
    ]
