# Generated by Django 4.2.6 on 2024-02-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0014_deviceos_devicebasicinfo_device_os"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicemanagement",
            name="start_ma_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
