# Generated by Django 4.2.6 on 2024-02-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0015_alter_devicemanagement_start_ma_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicemanagement",
            name="end_hw_support_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="devicemanagement",
            name="end_license_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="devicemanagement",
            name="end_ma_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="devicemanagement",
            name="end_sw_support_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="devicemanagement",
            name="start_license_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="devicemanagement",
            name="start_used_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
