# Generated by Django 4.2.6 on 2024-02-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0016_alter_devicemanagement_end_hw_support_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceinterface",
            name="list_interface_desc",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="deviceinterface",
            name="list_interface_inuse",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="deviceinterface",
            name="list_interface_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="deviceinterface",
            name="list_interface_neighbor",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="deviceinterface",
            name="list_interface_speed",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="deviceinterface",
            name="list_interface_state",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="deviceinterface",
            name="list_interface_type",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="deviceinterface",
            name="list_interface_unuse",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="devicetopology",
            name="device_rack_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="devicetopology",
            name="device_rack_unit",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
