# Generated by Django 4.2.6 on 2024-02-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_deviceinterface_list_interface_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicebasicinfo',
            name='device_stack',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicebasicinfo',
            name='device_ip',
            field=models.GenericIPAddressField(),
        ),
    ]
