# Generated by Django 4.2.6 on 2024-02-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_devicebasicinfo_device_stack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicebasicinfo',
            name='device_ip',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
