# Generated by Django 4.2.6 on 2024-02-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_devicebasicinfo_device_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemanagement',
            name='device_serial_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
