# Generated by Django 4.2.6 on 2024-02-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0020_alter_devicemanagement_device_serial_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicebasicinfo",
            name="device_stack",
            field=models.BooleanField(default=False),
        ),
    ]
