# Generated by Django 4.2.6 on 2024-02-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0021_alter_devicebasicinfo_device_stack"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicebasicinfo",
            name="device_firmware",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="devicebasicinfo",
            name="device_description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="devicebasicinfo",
            name="device_stack",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
