# Generated by Django 4.2.6 on 2024-02-06 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0023_deviceconfiguration_user_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicebasicinfo",
            name="device_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.devicelocation",
            ),
        ),
    ]
