# Generated by Django 4.2.6 on 2024-02-06 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0024_alter_devicebasicinfo_device_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_status", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="devicebasicinfo",
            name="device_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.devicecategory",
            ),
        ),
        migrations.AlterField(
            model_name="devicebasicinfo",
            name="device_os",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.deviceos"
            ),
        ),
        migrations.AlterField(
            model_name="devicebasicinfo",
            name="device_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.devicetype"
            ),
        ),
        migrations.AlterField(
            model_name="devicebasicinfo",
            name="device_vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.devicevendor"
            ),
        ),
        migrations.AddField(
            model_name="devicebasicinfo",
            name="device_status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.devicestatus",
            ),
            preserve_default=False,
        ),
    ]
