# Generated by Django 4.2.6 on 2024-02-06 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory",
            "0025_devicestatus_alter_devicebasicinfo_device_category_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="devicebasicinfo",
            name="device_status",
        ),
        migrations.DeleteModel(
            name="DeviceStatus",
        ),
    ]
