# Generated by Django 4.2.6 on 2024-02-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0026_remove_devicebasicinfo_device_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceconfiguration",
            name="device_backup_config",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deviceconfiguration",
            name="device_config_standardized",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deviceconfiguration",
            name="device_monitored",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
