# Generated by Django 4.2.6 on 2024-02-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0027_alter_deviceconfiguration_device_backup_config_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceinterface",
            name="list_interface_desc",
            field=models.JSONField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="deviceinterface",
            name="list_interface_inuse",
            field=models.JSONField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="deviceinterface",
            name="list_interface_name",
            field=models.JSONField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="deviceinterface",
            name="list_interface_neighbor",
            field=models.JSONField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="deviceinterface",
            name="list_interface_speed",
            field=models.JSONField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="deviceinterface",
            name="list_interface_state",
            field=models.JSONField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="deviceinterface",
            name="list_interface_type",
            field=models.JSONField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="deviceinterface",
            name="list_interface_unuse",
            field=models.JSONField(blank=True, max_length=200, null=True),
        ),
    ]
