# Generated by Django 4.2.6 on 2024-02-22 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0028_alter_deviceinterface_list_interface_desc_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deviceinterface",
            name="count_interface",
        ),
        migrations.RemoveField(
            model_name="deviceinterface",
            name="list_interface_inuse",
        ),
        migrations.RemoveField(
            model_name="deviceinterface",
            name="list_interface_neighbor",
        ),
        migrations.RemoveField(
            model_name="deviceinterface",
            name="list_interface_unuse",
        ),
    ]
