# Generated by Django 5.0.2 on 2024-02-22 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_remove_deviceinterface_count_interface_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFirmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmware', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(blank=True, max_length=100, null=True)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.devicetype')),
            ],
        ),
    ]
