# Generated by Django 5.0.2 on 2024-02-23 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_devicefirmware'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceBasicInfo',
            new_name='Device',
        ),
    ]
