# Generated by Django 4.2.6 on 2023-10-24 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IpProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IpStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IpSubnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipplan.iplocation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipplan.ipproject')),
            ],
        ),
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('description', models.CharField(max_length=1000)),
                ('user_request', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(max_length=100)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipplan.ipstatus')),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipplan.ipsubnet')),
            ],
        ),
    ]
