# Generated by Django 4.2.6 on 2023-10-25 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpRegoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regoin', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='ipmodel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ipsubnet',
            name='project',
        ),
        migrations.AlterField(
            model_name='iplocation',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='iplocation',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ipsubnet',
            name='subnet',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='IpProject',
        ),
        migrations.DeleteModel(
            name='IpStatus',
        ),
        migrations.AddField(
            model_name='iplocation',
            name='regoin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ipplan.ipregoin'),
            preserve_default=False,
        ),
    ]
