# Generated by Django 4.2.6 on 2024-07-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipplan', '0002_location_location_subnet_region_region_subnet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location_subnet',
        ),
        migrations.RemoveField(
            model_name='region',
            name='region_subnet',
        ),
    ]
