# Generated by Django 4.2.6 on 2023-10-25 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipplan', '0002_ipregoin_remove_ipmodel_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iplocation',
            name='regoin',
        ),
    ]
