# Generated by Django 4.2.6 on 2024-07-25 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipplan', '0003_remove_location_location_subnet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipaddressmodel',
            old_name='ip_address',
            new_name='ip',
        ),
    ]
