# Generated by Django 4.2.6 on 2023-10-25 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipplan', '0003_remove_iplocation_regoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='iplocation',
            name='regoin',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ipplan.ipregoin'),
            preserve_default=False,
        ),
    ]
