# Generated by Django 4.2.6 on 2023-10-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipplan', '0004_iplocation_regoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipsubnet',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
