# Generated by Django 4.2.6 on 2024-07-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipplan', '0004_rename_ip_address_ipaddressmodel_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnet',
            name='vlan',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
