# Generated by Django 4.2.6 on 2023-10-27 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipplan', '0005_ipsubnet_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IpModel',
            new_name='IpAddressModel',
        ),
    ]
