# Generated by Django 4.2.6 on 2024-07-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipplan', '0005_alter_subnet_vlan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddressmodel',
            name='ping_status',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ipaddressmodel',
            name='status',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='IpStatus',
        ),
    ]
