# Generated by Django 4.2.6 on 2023-10-27 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipplan', '0006_rename_ipmodel_ipaddressmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ipaddressmodel',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ipplan.ipstatus'),
            preserve_default=False,
        ),
    ]
