# Generated by Django 4.2.6 on 2024-07-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipplan', '0006_ipaddressmodel_ping_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddressmodel',
            name='ping_status',
        ),
    ]
