# Generated by Django 4.2.6 on 2023-10-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ipplan", "0008_remove_ipaddressmodel_user_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ipaddressmodel",
            name="ip_address",
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name="iplocation",
            name="location",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="ipregoin",
            name="regoin",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
