# Generated by Django 4.2.6 on 2023-10-30 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipplan', '0009_alter_ipaddressmodel_ip_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IpLocation',
            new_name='Location',
        ),
        migrations.RenameModel(
            old_name='IpRegoin',
            new_name='Region',
        ),
        migrations.RenameModel(
            old_name='IpSubnet',
            new_name='Subnet',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='regoin',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='regoin',
            new_name='region',
        ),
    ]
