# Generated by Django 4.2.6 on 2024-01-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipplan', '0010_rename_iplocation_location_rename_ipregoin_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddressmodel',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
